-- MySQL Script generated by MySQL Workbench
-- Thu Nov 26 17:54:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`atividade` (
  `pk_atividade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `mensalidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_atividade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instrutor` (
  `pk_instrutor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `CPF` CHAR(14) NOT NULL,
  PRIMARY KEY (`pk_instrutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma` (
  `pk_turma` INT NOT NULL AUTO_INCREMENT,
  `horario` VARCHAR(45) NOT NULL,
  `fk_atividade` INT NOT NULL,
  `fk_instrutor` INT NOT NULL,
  PRIMARY KEY (`pk_turma`),
  INDEX `fk_turma_atividade1_idx` (`fk_atividade` ASC) VISIBLE,
  INDEX `fk_turma_instrutor1_idx` (`fk_instrutor` ASC) VISIBLE,
  CONSTRAINT `fk_turma_atividade1`
    FOREIGN KEY (`fk_atividade`)
    REFERENCES `mydb`.`atividade` (`pk_atividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_instrutor1`
    FOREIGN KEY (`fk_instrutor`)
    REFERENCES `mydb`.`instrutor` (`pk_instrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `pk_aluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `peso` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`pk_aluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`matricula` (
  `pk_matricula` INT NOT NULL AUTO_INCREMENT,
  `turma_pk_turma` INT NOT NULL,
  `aluno_pk_aluno` INT NOT NULL,
  PRIMARY KEY (`pk_matricula`),
  INDEX `fk_matricula_turma1_idx` (`turma_pk_turma` ASC) VISIBLE,
  INDEX `fk_matricula_aluno1_idx` (`aluno_pk_aluno` ASC) VISIBLE,
  CONSTRAINT `fk_matricula_turma1`
    FOREIGN KEY (`turma_pk_turma`)
    REFERENCES `mydb`.`turma` (`pk_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_aluno1`
    FOREIGN KEY (`aluno_pk_aluno`)
    REFERENCES `mydb`.`aluno` (`pk_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
